# Generated by Django 3.1 on 2020-08-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=2500)),
                ('image', models.ImageField(blank=True, upload_to='articleImage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
